# PostgreSQL configuration
# Use DATABASE_URL in production (e.g., Neon serverless)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  <% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  database: afristream_development
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV["PGPORT"] || 5432 %>
  <% end %>

test:
  <<: *default
  <% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  database: afristream_test
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV["PGPORT"] || 5432 %>
  <% end %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # If Neon requires sslmode=require
  variables:
    sslmode: <%= ENV["PGSSLMODE"] || "require" %>
